#
#  Configuration file for BitWave Bio
#     https://github.com/BitWaveOrg
#

user_firstname: 'Nellex' # Username shown on profile (Required)
userbio: 'Поражение это всего лишь упущенная победа. Нет недостижимых целей, есть неправильные стратегии.' # Profile description (Required)

linkedin_login: '' # LinkedIn login (Optional)
telegram_login: 'nellex' # Telegram login (Optional)
discords_login: 'nellex_' # DiscordS login (Optional)
steam_login: '9259' # SteamCommunity ID (Optional)
instagram_login: 'nellexru' # Instagram login (Optional)
twitter_login: '' # Twitter login (Optional)
website_url: 'https://nellex.me' # Website url (Optional)
cv_url: '' # CV URL (Optional)

profile_theme: 'dark' # Profile style
profile_color: 'rgb(32, 34, 37)' # Profile border color
